#ifndef _MAIN_INCLUDE_H
#define _MAIN_INCLUDE_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <FreeRTOS.h>
#include <task.h>
#include <queue.h>
#include <timers.h>
#include <semphr.h>

#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "hardware/irq.h"
#include "hardware/timer.h"
#include "debug.h"
#include "bmc.pio.h" // Generated by PIOASM
#include "usb_pd/pd_frame.h"
#include "usb_pd/tcpc_bmc_phy.h"
#include "usb_pd/typec_4b5b.h"
#include "usb_pd/tcpc_task.h"
#include "usb_pd/crc32.h"
#include "cli/cli.h"

#endif
